SELECT TOP (1000) [codguion]
      ,[desguion]
      ,[cabguion]
      ,[codestru]
      ,[estado]
      ,[anuguion]
      ,[elevalor]
      ,[inctesti]
      ,[impindic]
      ,[juictasa]
      ,[planosit]
      ,[planopla]
      ,[ROWID]
  FROM [CORITEL].[dbo].[taoguion]