SELECT TOP (1000) [codapart]
      ,[desapart]
      ,[cabapart]
      ,[codestru]
      ,[orientac]
      ,[saltopag]
      ,[condicion]
      ,[ROWID]
      ,[FormulaPaso1]
      ,[FormulaPaso2]
      ,[FormulaPaso3]
      ,[FormulaSalida]
      ,[ClaseJavasCript]
      ,[FuncionTaoapartTituloCondicionJavascript]
      ,[ClaseJavasCript_respaldo]
      ,[FuncionTaoapartTituloCondicionJavascript_respaldo]
      ,[EsApartadoIndice]
  FROM [CORITEL].[dbo].[taoapart]

  class clsCodapart_00104 extends DATOSENCARGO{  #x; constructor(idApartado){super();this.#x=idApartado; } festado() {var rz=0; try { rz = parseInt(this.#x.getAttribute("data-estado"));} catch (e) {rz=0;} finally {} } fdevApartado (){return (this.#x);}fcondi()   {var rz=0;   try { if(1==1){ rz=1 ;}} catch (e) {rz=0;} finally {} switch (rz) {case 0 :  this.#x.className = "ApartadoOculto"; this.#x.setAttribute("data-estado",0 );  break; case 1 :   this.#x.className = "ApartadoVisible"; this.#x.setAttribute("data-estado",1 )   }     ;}   ##taoapartTituloCondicion## }