SELECT TOP (1000) [codtasad]
      ,[nudirect]
      ,[diretasa]
      ,[codposta]
      ,[codprovi]
      ,[codlocal]
      ,[tel1tasa]
      ,[tel2tasa]
      ,[faxtasa]
      ,[obsditas]
  FROM [CORITEL].[dbo].[taoditas]