SELECT TOP (1000) [codtasad]
      ,[dnitasad]
      ,[nomtasad]
      ,[ap1tasad]
      ,[ap2tasad]
      ,[numasign]
      ,[modcobta]
      ,[ctabanca]
      ,[ndircorr]
      ,[ndircobr]
      ,[codcabas]
      ,[anulado]
      ,[numbanco]
      ,[numsucur]
      ,[fecalta]
      ,[fecbaja]
      ,[observaciones]
      ,[encargoprueba]
      ,[numinforpruebas]
      ,[iban]
      ,[fecnac]
  FROM [CORITEL].[dbo].[taotasad]