SELECT TOP (1000) [USU_Codigo]
      ,[USU_Password]
      ,[USU_Descripcion]
      ,[USU_Tipo]
      ,[PER_Codigo]
      ,[USU_Identificador]
      ,[USU_Defecto1]
      ,[USU_Defecto2]
      ,[USU_Defecto3]
      ,[USU_Fecha]
      ,[USU_CambioPassword]
      ,[USU_Password1]
      ,[USU_Password2]
  FROM [CORITEL].[dbo].[iTH_Usuarios]