SELECT TOP (1000) [codigo]
      ,[fk_TH_Tasadores]
      ,[ficheros_cv]
      ,[fecha_incorporacion_cv]
      ,[ficheros_certificado_contratista]
      ,[fecha_incorporacion_certificado_contratista]
      ,[fecha_caducidad_certificado_contratista]
      ,[ficheros_seguro_responsabilidad_civil]
      ,[fecha_incorporacion_seguro_responsabilidad_civil]
      ,[fecha_caducidad_seguro_responsabilidad_civil]
      ,[codigo_control]
      ,[busqueda]
      ,[grid_busqueda]
      ,[flag_regenerar_grid_busqueda]
      ,[cascading]
      ,[ficheros_certificado_contratista_at]
      ,[fecha_caducidad_certificado_contratista_at]
      ,[fecha_incorporacion_certificado_contratista_at]
  FROM [ETHER].[dbo].[TH_Tasadores_Documentos]